# Generated by Django 5.1.2 on 2024-11-25 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kouryakusaito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('character', 'キャラクター'), ('enemy', '敵'), ('item', 'アイテム')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='kouryakupost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kouryakupost',
            name='category',
            field=models.CharField(choices=[('character', 'キャラクターのこと'), ('enemy', '敵のこと'), ('item', 'アイテムのこと')], max_length=50, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='kouryakupost',
            name='title',
            field=models.CharField(max_length=400, verbose_name='タイトル'),
        ),
    ]
