# Generated by Django 5.1.2 on 2024-11-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kouryakusaito', '0004_kouryakupost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('character', 'キャラクター'), ('enemy', '敵'), ('item', 'アイテム'), ('mynews', '最近の出来事')], max_length=10),
        ),
    ]
